export const CACHE = {
	GROUP: {
		GLOBAL :{
			NAME: "GLOBAL_CACHE",
			KEYS: {
				DEFAULT_CONFIG:"GLOBAL.DEFAULT",
				CONFIG:"GLOBAL.CONFIG",
				LOGGED_USER: "GLOBAL.LOGGED_USER",
				CLASSLOADER: "GLOBAL.CLASSLOADER"
			}
		},
		DASHBOARD:{
			NAME: 'DASHBOARD_CACHE',
			KEYS: {
				
			}
		}
	}
}